name: "Publish Performance Analysis Report"
description: "Generate, and publish a markdown Android performance analysis report from benchcomp"

inputs:
  artifact-prefix:
    description: "Artifact name prefix"
    required: false
    default: "benchcomp"
  github-token:
    description: "GitHub token with pull-requests:write and actions:read permissions"
    required: false
    default: ${{ github.token }}
  upload-artifact-name:
    description: "Path of the upload artifact"
    required: false
    default: "benchcomp-report.md"
  comment-on-pr:
    description: "Whether to comment results on the PR"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Fetch Artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: "${{ inputs.prefix }}"
        github-token: ${{ inputs.github-token }}
        path: ".artifacts"
        merge-multiple: true

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install Benchmarkdown
      shell: bash
      run: pip install git+https://github.com/Frozen-Bytes/benchmarkdown.git@v1.0.0

    - name: Generate Markdown Report
      shell: bash
      run: benchmarkdown -o "${{ inputs.upload-artifact-name }}" -- .artifacts/

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v7
      with:
        name: "${{ inputs.upload-artifact-name }}"
        path: "${{ inputs.upload-artifact-name }}"
        archive: false

    - name: Comment Results on Pull Request
      if: ${{ inputs.comment-on-pr == 'true' }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        gh pr comment "${{ github.event.pull_request.number }}" \
          --repo "${{ github.repository }}" \
          --body-file "${{ inputs.upload-artifact-name }}"
